framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: true
    trusted_hosts: ~
    session:
        handler_id: ~
        cookie_secure: auto
        cookie_samesite: lax
    esi: true
    fragments: true
    php_errors:
        log: true
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
    ide: ~
    validation:
        email_validation_mode: 'html5'
        enable_annotations: true

